In [3]:
# import library

import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler 
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder 
from sklearn.preprocessing import OneHotEncoder

In [69]:
# tampilkan record

df = pd.read_csv('players_fifa.csv')
df.head(10)

team  number position  birth_date  shirt_name          club  height  \
0  Argentina       1       GK  1986-02-10      GUZMÁN   Tigres UANL     192   
1  Argentina       2       DF  1987-03-18     MERCADO    Sevilla FC     181   
2  Argentina       3       DF  1992-08-31  TAGLIAFICO      AFC Ajax     169   
3  Argentina       4       DF  1986-09-20     ANSALDI     Torino FC     181   
4  Argentina       5       MF  1986-01-30      BIGLIA      AC Milan     175   
5  Argentina       6       DF  1987-03-17       FAZIO       AS Roma     199   
6  Argentina       7       MF  1988-06-29      BANEGA    Sevilla FC     175   
7  Argentina       8       DF  1991-10-28       ACUÑA   Sporting CP     172   
8  Argentina       9       FW  1987-12-10     HIGUAÍN   Juventus FC     184   
9  Argentina      10       FW  1987-06-24       MESSI  FC Barcelona     170   

   weight league        age                name  caps  
0      90    MEX  32.339726       Nahuel Guzmán     6  
1      81    ESP  31.241096     Gabriel Mercado    20  
2      65    NED  25.786301  Nicolás Tagliafico     4  
3      73    ITA  31.731507    Cristian Ansaldi     5  
4      73    ITA  32.369863        Lucas Biglia    57  
5      85    ITA  31.243836      Federico Fazio     9  
6      73    ESP  29.958904         Éver Banega    62  
7      77    POR  26.627397        Marcos Acuña    10  
8      75    ITA  30.509589     Gonzalo Higuaín    71  
9      72    ESP  30.972603        Lionel Messi   124

In [89]:
# bagi dataset menjadi training set dan test set dengan proporsi 70:30

data  = df[['number','age','weight','height']]
label = df['caps']

data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=.3)

In [90]:
# Lakukan normalisasi data pada salah satu attribute menggunakan Min Max scaler

normalisasi = df.copy()
standarirasi = df.copy()

In [91]:
scaler = MinMaxScaler()

normalize_dataset = MinMaxScaler().fit_transform(normalisasi[['number','age','weight','height']])

In [92]:
normalize_dataset = pd.DataFrame(normalize_dataset)
normalize_dataset.head(5)

0         1      2         3
0  0.000000  0.496677  0.775  0.750000
1  0.045455  0.454373  0.550  0.444444
2  0.090909  0.244330  0.150  0.111111
3  0.136364  0.473257  0.350  0.444444
4  0.181818  0.497837  0.350  0.277778

In [93]:
# Lakukan standarisasi pada dataset

standarirasi.drop(['team','birth_date','shirt_name','club','league','name','position'], axis=1, inplace=True)

standarirasi

number  height  weight        age  caps
0         1     192      90  32.339726     6
1         2     181      81  31.241096    20
2         3     169      65  25.786301     4
3         4     181      73  31.731507     5
4         5     175      73  32.369863    57
..      ...     ...     ...        ...   ...
731      19     196      89  27.684932    30
732      20     172      66  28.238356     4
733      21     188      78  31.328767   101
734      22     178      75  31.186301    76
735      23     187      82  35.221918    11

[736 rows x 5 columns]

In [94]:
standart_std = StandardScaler()

scaled_data = standart_std.fit_transform(standarirasi)

print('Dataset sebelum scalling:',  # SEBELUM
      f'Nilai standar deviasi:\n{np.std(standarirasi)}',
      sep='\n', end='\n\n')

print('Dataset setelah scalling:',  # SESUDAH
      scaled_data[:6],
      f'Nilai standar deviasi: {np.std(scaled_data)}',
      sep='\n')

Dataset sebelum scalling:
Nilai standar deviasi:
number     6.633250
height     6.926214
weight     7.228862
age        3.913308
caps      31.910380
dtype: float64

Dataset setelah scalling:
[[-1.6583124   1.38494005  1.77222093  1.13598006 -0.9190992 ]
 [-1.50755672 -0.20322916  0.52721176  0.85523801 -0.48037048]
 [-1.35680105 -1.93577739 -1.68613787 -0.53867076 -0.98177473]
 [-1.20604538 -0.20322916 -0.57946305  0.98055678 -0.95043697]
 [-1.05528971 -1.06950328 -0.57946305  1.14368121  0.67912685]
 [-0.90453403  2.39559318  1.08054917  0.85593812 -0.8250859 ]]
Nilai standar deviasi: 1.0


In [95]:
# cek data null

df.isna().sum()

# tidak ada data yang bernilai null

team          0
number        0
position      0
birth_date    0
shirt_name    0
club          0
height        0
weight        0
league        0
age           0
name          0
caps          0
dtype: int64

In [97]:
# Lakukan Data cleaning pada data dengan nilai duplikat

standarisasi = df.copy()
standarisasi.duplicated().sum()

# tidak ada data yang duplikat

0

In [98]:
# drop data duplikat

standarisasi.drop_duplicates(inplace=True)

standarisasi.duplicated().sum()

0

In [99]:
# Ganti tipe data salah satu attribute angka

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   team        736 non-null    object 
 1   number      736 non-null    int64  
 2   position    736 non-null    object 
 3   birth_date  736 non-null    object 
 4   shirt_name  736 non-null    object 
 5   club        736 non-null    object 
 6   height      736 non-null    int64  
 7   weight      736 non-null    int64  
 8   league      736 non-null    object 
 9   age         736 non-null    float64
 10  name        736 non-null    object 
 11  caps        736 non-null    int64  
dtypes: float64(1), int64(4), object(7)
memory usage: 69.1+ KB


In [104]:
dat = {'caps':float}
pd.options.display.float_format = '{:.1f}'.format
df['caps'] = df['caps'].astype('float64')

In [105]:
df.head(100)

team  number position  birth_date  shirt_name               club  \
0   Argentina       1       GK  1986-02-10      GUZMÁN        Tigres UANL   
1   Argentina       2       DF  1987-03-18     MERCADO         Sevilla FC   
2   Argentina       3       DF  1992-08-31  TAGLIAFICO           AFC Ajax   
3   Argentina       4       DF  1986-09-20     ANSALDI          Torino FC   
4   Argentina       5       MF  1986-01-30      BIGLIA           AC Milan   
..        ...     ...      ...         ...         ...                ...   
95   Colombia       4       DF  1992-01-13       ARIAS      PSV Eindhoven   
96   Colombia       5       MF  1993-10-16     BARRIOS    CA Boca Juniors   
97   Colombia       6       MF  1986-02-06  C. SANCHEZ       RCD Espanyol   
98   Colombia       7       FW  1986-09-08       BACCA      Villarreal CF   
99   Colombia       8       MF  1985-01-06  AGUILAR T.  AC Deportivo Cali   

    height  weight league  age                name  caps  
0      192      90    MEX 32.3       Nahuel Guzmán   6.0  
1      181      81    ESP 31.2     Gabriel Mercado  20.0  
2      169      65    NED 25.8  Nicolás Tagliafico   4.0  
3      181      73    ITA 31.7    Cristian Ansaldi   5.0  
4      175      73    ITA 32.4        Lucas Biglia  57.0  
..     ...     ...    ...  ...                 ...   ...  
95     177      71    NED 26.4      Santiago Arias  41.0  
96     178      74    ARG 24.7      Wílmar Barrios  10.0  
97     182      82    ESP 32.4      Carlos Sánchez  85.0  
98     181      77    ESP 31.8        Carlos Bacca  45.0  
99     185      82    COL 33.4        Abel Aguilar  70.0  

[100 rows x 12 columns]

In [106]:
df['club'].value_counts()

Manchester City FC        16
Real Madrid CF            15
FC Barcelona              14
Tottenham Hotspur FC      12
Paris Saint-Germain FC    12
                          ..
Jeju United                1
Seongnam FC                1
Ulsan Hyundai FC           1
Asan Mugunghwa FC          1
CR Vasco da Gama           1
Name: club, Length: 310, dtype: int64

In [115]:
# Lakukan one hot encoding pada dataset

OneHot = df.copy()

df['club'].unique()

array(['Tigres UANL', 'Sevilla FC', 'AFC Ajax', 'Torino FC', 'AC Milan',
       'AS Roma', 'Sporting CP', 'Juventus FC', 'FC Barcelona',
       'Paris Saint-Germain FC', 'CA River Plate', 'CA Independiente',
       'Hebei China Fortune FC', 'West Ham United FC',
       'Manchester United FC', 'Manchester City FC', 'SL Benfica',
       'CA Boca Juniors', 'Chelsea FC', 'Brighton & Hove Albion FC',
       'Yokohama F-Marinos', 'Millwall FC', 'Al Ahli SC',
       'Suwon Samsung Bluewings FC', 'Hertha BSC',
       'Queens Park Rangers FC', 'FC Luzern', 'VfL Bochum', 'Urawa Reds',
       'Feyenoord Rotterdam', 'Huddersfield Town FC', 'Hibernian FC',
       'Aston Villa FC', 'Bursaspor', 'Melbourne City FC', 'KRC Genk',
       'WS Wanderers FC', 'Grasshopper Club', 'Newcastle United Jets FC',
       'Hull City FC', 'Celtic FC', 'Tottenham Hotspur FC',
       'Tianjin Quanjian FC', 'Dalian Yifang FC', 'Liverpool FC',
       'VfL Wolfsburg', 'SSC Napoli', 'VfL Borussia Mönchengladbach',
       

In [116]:
temp_dataset = pd.get_dummies(OneHot[['club']])

temp_dataset = pd.DataFrame(temp_dataset)

OneHot.drop('club', axis=1, inplace=True)

OneHot = OneHot.join(temp_dataset)
OneHot.head(10)

team  number position  birth_date  shirt_name  height  weight league  \
0  Argentina       1       GK  1986-02-10      GUZMÁN     192      90    MEX   
1  Argentina       2       DF  1987-03-18     MERCADO     181      81    ESP   
2  Argentina       3       DF  1992-08-31  TAGLIAFICO     169      65    NED   
3  Argentina       4       DF  1986-09-20     ANSALDI     181      73    ITA   
4  Argentina       5       MF  1986-01-30      BIGLIA     175      73    ITA   
5  Argentina       6       DF  1987-03-17       FAZIO     199      85    ITA   
6  Argentina       7       MF  1988-06-29      BANEGA     175      73    ESP   
7  Argentina       8       DF  1991-10-28       ACUÑA     172      77    POR   
8  Argentina       9       FW  1987-12-10     HIGUAÍN     184      75    ITA   
9  Argentina      10       FW  1987-06-24       MESSI     170      72    ESP   

   age                name  ...  club_Watford FC  \
0 32.3       Nahuel Guzmán  ...                0   
1 31.2     Gabriel Mercado  ...                0   
2 25.8  Nicolás Tagliafico  ...                0   
3 31.7    Cristian Ansaldi  ...                0   
4 32.4        Lucas Biglia  ...                0   
5 31.2      Federico Fazio  ...                0   
6 30.0         Éver Banega  ...                0   
7 26.6        Marcos Acuña  ...                0   
8 30.5     Gonzalo Higuaín  ...                0   
9 31.0        Lionel Messi  ...                0   

   club_West Bromwich Albion FC  club_West Ham United FC  \
0                             0                        0   
1                             0                        0   
2                             0                        0   
3                             0                        0   
4                             0                        0   
5                             0                        0   
6                             0                        0   
7                             0                        0   
8                             0                        0   
9                             0                        0   

   club_Wigan Athletic FC  club_Wolverhampton Wanderers FC  \
0                       0                                0   
1                       0                                0   
2                       0                                0   
3                       0                                0   
4                       0                                0   
5                       0                                0   
6                       0                                0   
7                       0                                0   
8                       0                                0   
9                       0                                0   

   club_Yeni Malatyaspor  club_Yokohama F-Marinos  club_Zamalek  \
0                      0                        0             0   
1                      0                        0             0   
2                      0                        0             0   
3                      0                        0             0   
4                      0                        0             0   
5                      0                        0             0   
6                      0                        0             0   
7                      0                        0             0   
8                      0                        0             0   
9                      0                        0             0   

   club_Zob Ahan Isfahan FC  club_Étoile du Sahel  
0                         0                     0  
1                         0                     0  
2                         0                     0  
3                         0                     0  
4                         0                     0  
5                         0                     0  
6                         0                     0  
7                         0                     0  
8   